stage1:
  ranks: 2
  steps: 2
  read_size_bytes: 1024         # 1 KiB pre-step read
  write_size_bytes: 1342177280  # 1.25 GiB post-step write
  device: "cpu"                 # "cpu" or "gpu"
  matmul_dim: 8192              # dimension for square matrix multiplication

stage2:
  ranks: 4
  steps: 2
  read_size_bytes: 1048576      # 1 MiB pre-step read
  write_size_bytes: 2147483648  # 2 GiB post-step write
  device: "cpu"                 # "cpu" or "gpu"
  matmul_dim: 2048              # dimension for square matrix multiplication

stage3:
  ranks: 8
  steps: 2
  read_size_bytes: 2147483648   # 2 GiB pre-step read
  write_size_bytes: 512         # 512 B post-step write
  data_copy_size_bytes: 2097152 # 2 MiB data copy
  matmul_dim: 8192              # dimension for square matrix multiplication

stage4:
  ranks: 16
  steps: 2
  read_size_bytes: 1342177280   # 1.25 GiB pre
  write_size_bytes: 2147483648  # 2 GiB post-step write
  data_copy_size_bytes: 2097152 # 2 MiB data copy
  matmul_dim: 8192              # dimension for square matrix multiplication
